VALID_TASK_STATUSES = ["pending", "in_progress", "done", "cancelled"]
VALID_USER_ROLES = ["user", "admin", "manager"]

TASK_TITLE_MIN_LENGTH = 3
TASK_TITLE_MAX_LENGTH = 200
TASK_PRIORITY_MIN = 1
TASK_PRIORITY_MAX = 5

MIN_PASSWORD_LENGTH = 4
DEFAULT_PRIORITY = 3
DEFAULT_CATEGORY_COLOR = "#000000"
RECENT_ACTIVITY_DAYS = 7
